dynaconf_merge = true

[default]
  testing = false
  [default.api]
    storage_http_protocol = 'https'
    storage_port = '443'
    ws_timeout = 2
    upload_study_timeout = 200

[testing]
  testing = true
  test_account_name = 'PYTHON_SDK_TEST_ACCOUNT'
  [testing.api]
    url = "https://local.ambrahealth.dev/api/v3"
    username = 'username'
    password = 'password'

[development]
  [development.api]
    url = "https://local.ambrahealth.dev/api/v3"
    username = 'username'
    password = 'password'
